#
## Copyright (c) 2025 Wind River Systems, Inc.
##
## SPDX-License-Identifier: Apache-2.0
#
#    - Auto Updated Contents 2025-04-11 18:08:12 -

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: kernel-module-management-app
  labels:
    chart_group: starlingx-kernel-module-management-charts
spec:
  releaseName: kernel-module-management-app
  chart:
    spec:
      chart: kernel-module-management-app
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: kernel-module-management-static-overrides
      valuesKey: kernel-module-management-static-overrides.yaml
    - kind: Secret
      name: kernel-module-management-system-overrides
      valuesKey: kernel-module-management-system-overrides.yaml
