apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
    control-plane: controller
  name: {{ .Values.namespace }}
---
