apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
    control-plane: controller
  name: kmm-operator-controller-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
    control-plane: controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/created-by: kernel-module-management
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
  name: kmm-operator-webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
    control-plane: webhook-server
---
