apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
  name: kmm-operator-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kmm-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: kmm-operator-controller
  namespace: {{ .Values.namespace }}
---
